"""Initial migration

Revision ID: 12f30bae022c
Revises: 
Create Date: 2026-01-13 00:58:22.957073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f30bae022c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'OFF_DUTY', name='courierstatus'), nullable=True),
    sa.Column('max_capacity', sa.Float(), nullable=True),
    sa.Column('current_load', sa.Float(), nullable=True, server_default='0.0'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_couriers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_couriers_name'), ['name'], unique=False)

    op.create_table('delivery_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPTIMIZING', 'READY', 'COMPLETED', name='planstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('algorithm_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_plans_id'), ['id'], unique=False)

    op.create_table('delivery_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('geo_json', sa.JSON(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('estimated_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['delivery_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_routes_id'), ['id'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_phone', sa.String(), nullable=True),
    sa.Column('recipient_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True, server_default='1.0'),
    sa.Column('volume', sa.Float(), nullable=True, server_default='0.1'),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'FAILED', name='packagestatus'), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['delivery_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_tracking_number'), ['tracking_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_packages_id'))

    op.drop_table('packages')
    with op.batch_alter_table('delivery_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_routes_id'))

    op.drop_table('delivery_routes')
    with op.batch_alter_table('delivery_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_plans_id'))

    op.drop_table('delivery_plans')
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_couriers_name'))
        batch_op.drop_index(batch_op.f('ix_couriers_id'))

    op.drop_table('couriers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_name'))
        batch_op.drop_index(batch_op.f('ix_stations_id'))

    op.drop_table('stations')
    # ### end Alembic commands ###
