"""update_courier_capacity_float

Revision ID: 20d0ae324fa8
Revises: 44b1682e5778
Create Date: 2026-01-13 06:19:00.059115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d0ae324fa8'
down_revision: Union[str, Sequence[str], None] = '44b1682e5778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.alter_column('max_capacity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.alter_column('max_capacity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
